openapi: 3.0.3

info:
  version: 0.1.0
  title: 'Products REST API'
  description: |-
    Products API is a RESTful API based in the product taxonomy of Mercado Libre.
    You will access hundreds of products which have basic information such as images,
    price, category, description and taxonomic information of the product.
  termsOfService: TERMS_OF_SERVICE
  license:
    name: MIT
    url: https://github.com/sandersgutierrez/products-api/blob/main/LICENSE
  contact:
    name: Sanders Gutiérrez
    url: https://sandersgutierrez.github.io
    email: ing.sanders@gmail.com

tags:
  - name: Products
    description: Everything about Products

servers:
  - url: http://{host}:{port}/api/{basePath}
    description: Local server
    variables:
      host:
        default: '127.0.0.1'
      port:
        enum:
        - '3000'
        - '443'
        default: '3000'
      basePath:
        default: v1

paths:
  /products:
    get:
      tags:
        - Products
      summary: Get all products
      responses:
        200:
          description: A JSON array of products
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/Product'
        404:
          description: Return message when is not possible found products
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      tags:
        - Products
      summary: Create a product
      responses:
        201:
          description: A new product have been created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /products/{productId}:
    parameters:
      - name: productId
        description: The unique identifier of the product
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/ProductId'
    get:
      tags:
        - Products
      summary: Read a product
      responses:
        200:
          description: The product corresponding to the provided `productId`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        404:
          description: No product found for the provided `productId`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      tags:
        - Products
      summary: Update a product
      responses:
        200:
          description: The product corresponding to the provided `productId`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        404:
          description: No product found for the provided `productId`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    CategoryId:
      type: string
      description: The unique identifier of a category
    Category:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/CategoryId'
        name:
          type: string
    ProductId:
      type: string
      description: The unique identifier of a product
    Product:
      type: object
      required:
        - name
        - photo
        - price
        - category
        - description
      properties:
        id:
          $ref: '#/components/schemas/ProductId'
        name:
          type: string
        photo:
          type: string
        price:
          type: number
        category:
          $ref: '#/components/schemas/Category'
        description:
          type: string
    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: A human readable error message
